<?xml version="1.0" encoding="utf-8"?><Database Name="AHNO_BGC_2012" Class="AHNODataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=dev3.azaz.com;Initial Catalog=AHNO_BGC_2012;Persist Security Info=True;User ID=pchavali" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AHNO_BGC_2012ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_VEHICLE_MAKE" Member="VehicleMakes">
    <Type Name="VehicleMake">
      <Column Name="VMAKE_ID" Member="Identifier" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VMAKE_DESC" Member="MakeDescription" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VMAKE_CODE" Member="MakeCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VMAKE_STATUS" Member="Status" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VMAKE_TS" Member="CreatedDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_VEHICLE_MODEL" Member="VehicleModels">
    <Type Name="VehicleModel">
      <Column Name="VMODEL_ID" Member="Identifier" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VMODEL_VMAKE_CODE" Member="MakeCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VMODEL_TYPE" Member="ModelType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VMODEL_CODE" Member="ModelCode" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="VMODEL_DESC" Member="ModelDescription" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VMODEL_GM" Member="ModelGM" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VMODEL_CURRENT_GM" Member="ModelCurrentGM" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VMODEL_STATUS" Member="Status" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VMODEL_TS" Member="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_STATE" Member="States">
    <Type Name="State">
      <Column Name="stt_id" Member="Identifier" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="stt_state_code" Member="StateCode" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="stt_description" Member="StateDescription" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="stt_create_uid" Member="CreatedUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stt_update_uid" Member="UpdatedUID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stt_create_ts" Member="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="stt_update_ts" Member="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="stt_status" Member="Status" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_COUPON_CODES" Member="TBL_COUPON_CODEs">
    <Type Name="TBL_COUPON_CODE">
      <Column Name="CP_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CP_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CP_PIN" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CP_PROGRAM_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CP_STATUS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CP_REDEEM_TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CP_CREATED_TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CP_UPDATED_TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CP_USERID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PROGRAMS" Member="TBL_PROGRAMs">
    <Type Name="TBL_PROGRAM">
      <Column Name="P_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="P_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="P_STATUS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="P_TS" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_REGISTRATION_QA" Member="TBL_REGISTRATION_QAs">
    <Type Name="TBL_REGISTRATION_QA">
      <Column Name="VQD_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VQD_UID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VQD_PRGM_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VQD_Q_CODE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="VQD_A_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VAQ_TS" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_TOURNAMENT_CARD_CODES" Member="TBL_TOURNAMENT_CARD_CODEs">
    <Type Name="TBL_TOURNAMENT_CARD_CODE">
      <Column Name="CT_CARD_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CT_PROGRAM_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CT_TOURNAMENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CT_CARD_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CT_CARD_STATUS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CT_CARD_RETURN" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CT_CARD_TS" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_DEALER_INFORMATION" Member="TBL_DEALER_INFORMATIONs">
    <Type Name="TBL_DEALER_INFORMATION">
      <Column Name="D_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="D_BAC" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="D_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="D_NAME" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="D_ADDRESS" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="D_CITY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="D_STATE" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="D_ZIP" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="D_GM_Region" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="D_ZONE_NAME" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="D_ZONE_MANAGER" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="D_DISTRICT_NAME" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="D_DISTRICT_MANAGER" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="D_STATUS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="D_TS" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_REGION" Member="TBL_REGIONs">
    <Type Name="TBL_REGION">
      <Column Name="R_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="R_CODE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="R_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="R_STATUS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="R_TS" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_TOURNAMENT" Member="TBL_TOURNAMENTs">
    <Type Name="TBL_TOURNAMENT">
      <Column Name="T_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="T_NAME" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="T_REGION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="T_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="T_EXPIRY_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="T_DEALER_NAME" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="T_STREET" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="T_CITY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="T_STATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="T_ZIP" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="T_CONTRACT_ID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="T_CARD_RETURN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="T_BAC_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="T_ZONE_NAME" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="T_ZONE_MANAGER" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="T_DISTRICT_NAME" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="T_DISTRICT_MANAGER" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="T_IPADDRESS" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="T_WEB_WATCH" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="T_STATUS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="T_TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_REGISTRATION" Member="TBL_REGISTRATIONs">
    <Type Name="TBL_REGISTRATION">
      <Column Name="R_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="R_PREF_TITLE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="R_FIRST_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="R_LAST_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="R_ADDRESS" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="R_CITY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="R_STATE" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="R_ZIPCODE" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="R_EMAIL" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="R_PHONE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="R_PH_TYPE" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="R_PROGRAM_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R_CARD_NUMBER" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="R_COUPON_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R_TOUR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R_TOUR_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="R_CONTRACT_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="R_PLANNING" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="R_MODEL_INFORMATION" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="R_LOCAL_DEALER" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="R_CONTACT_DEALER" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="R_CONTACT_DEALER_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="R_TIME_FRAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="R_INTEREST_VECHILE" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="R_CURR_HH_MAKE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="R_CURR_HH_MODEL" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="R_CURR_HH_MAKE_OTHER" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="R_CURR_HH_MODEL_OTHER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="R_CURR_HH_YEAR" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="R_CURR_HH_MAKE2" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="R_CURR_HH_MODEL2" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="R_CURR_HH_MAKE_OTHER2" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="R_CURR_HH_MODEL_OTHER2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RR_CURR_HH_YEAR2" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="R_BAC_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="R_DEALER_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R_DEALER_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="R_DEALER_NAME" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="R_DEALER_EMAIL" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="R_SALESPERSON_NAME" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="R_SALESPERSON_EMAIL" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="R_TEST_DRIVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="R_TEST_DRIVE_MAKE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="R_TEST_DRIVE_MODEL" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="R_TEST_DRIVE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="R_SECONDARY_TEST_DRIVE_MAKE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="R_SECONDARY_TEST_DRIVE_MODEL" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="R_SECONDARY_TEST_DRIVE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="R_SOURCE_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="R_STATUS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="R_IPADDRESS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="R_AUTHENTICATION" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="R_CREATED_TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="R_UPDATED_TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="R_USERID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="R_MAIL_STATUS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="R_MAIL_TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="R_ALT_MAIL" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="R_MAIL_SENT_TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.usp_Registration_Customer_QA" Method="usp_Registration_Customer_QA">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="prgm_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="que_code" Type="System.String" DbType="VarChar(1500)" />
    <Parameter Name="ans_code" Type="System.String" DbType="VarChar(1500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_GetCustomer_Info" Method="usp_GetCustomer_Info">
    <Parameter Name="c_card_Code" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="c_program_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="c_d_code" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="errorno" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_RegMalling" Method="usp_RegMalling">
    <Parameter Name="cust_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>